<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-D2GVCL39" ignored="10" name="Regression" tests="43" failures="13" timestamp="2022-12-06T21:07:54 IST" time="235.493" errors="0">
  <testcase name="a" time="0.005" classname="misleneouse.PriorityClass"/>
  <testcase name="b" time="0.002" classname="misleneouse.PriorityClass"/>
  <testcase name="aMethod" time="0.002" classname="misleneouse.PriorityClass"/>
  <testcase name="bMethod" time="0.002" classname="misleneouse.PriorityClass"/>
  <testcase name="d" time="0.003" classname="misleneouse.PriorityClass"/>
  <testcase name="cMethod" time="0.008" classname="misleneouse.PriorityClass"/>
  <testcase name="brockenLinkMethod" time="1.355" classname="brockenlink.BrockenLinkClass"/>
  <testcase name="brockenLinkMethod" time="28.982" classname="brockenlink.BrockenLinkClass3"/>
  <testcase name="brockenLinkMethod" time="31.778" classname="brockenlink.BrockenLinkClass4"/>
  <testcase name="brockenLinkMethod" time="43.436" classname="brockenlink.BrockenLinkClass5"/>
  <testcase name="toVerifyUsedCanSendEmail" time="0.058" classname="misleneouse.DependentTestCases">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Username is not matching expected [ertertet] but found [ABCD]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Username is not matching expected [ertertet] but found [ABCD]
at misleneouse.DependentTestCases.toVerifyUsedCanSendEmail(DependentTestCases.java:29)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- toVerifyUsedCanSendEmail -->
  <testcase name="toVerifyUserCanLoginWithValidUserNameAndPassword" time="0.003" classname="misleneouse.DependentTestCases"/>
  <testcase name="toVerifyUserCanLoginWithValidUserNameAndPassword" time="0.017" classname="annotations.AnnotationClass"/>
  <testcase name="toVerifyUserCanNotLoginWithInvalidCredentials" time="0.014" classname="annotations.AnnotationClass"/>
  <testcase name="toVerifyUserCanLoginWithValidUserNameAndPassword" time="0.015" classname="assertions.AssertsInTestNG">
    <failure type="java.lang.AssertionError" message="User name is not displayed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: User name is not displayed expected [true] but found [false]
at assertions.AssertsInTestNG.toVerifyUserCanLoginWithValidUserNameAndPassword(AssertsInTestNG.java:15)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- toVerifyUserCanLoginWithValidUserNameAndPassword -->
  <testcase name="toVerifyUserCanNotLoginWithInvalidCredentials" time="0.006" classname="assertions.AssertsInTestNG">
    <failure type="java.lang.AssertionError" message="Username is not matching expected [abcd] but found [ABCD]">
      <![CDATA[java.lang.AssertionError: Username is not matching expected [abcd] but found [ABCD]
at assertions.AssertsInTestNG.toVerifyUserCanNotLoginWithInvalidCredentials(AssertsInTestNG.java:24)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- toVerifyUserCanNotLoginWithInvalidCredentials -->
  <testcase name="verifyUserCanBeDeleted" time="0.005" classname="assertions.AssertsInTestNG">
    <failure type="java.lang.AssertionError" message="Object still null expected object to not be null">
      <![CDATA[java.lang.AssertionError: Object still null expected object to not be null
at assertions.AssertsInTestNG.verifyUserCanBeDeleted(AssertsInTestNG.java:34)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserCanBeDeleted -->
  <testcase name="verifyUserCountGetsReduced" time="0.003" classname="assertions.AssertsInTestNG">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at assertions.AssertsInTestNG.verifyUserCountGetsReduced(AssertsInTestNG.java:41)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserCountGetsReduced -->
  <testcase name="toVerifyUserCanLoginWithValidUserNameAndPassword" time="0.002" classname="assertions.SoftAssertsInTestNG">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	User name is not displayed expected [true] but found [false],
	Sign up option is still displayed expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
User name is not displayed expected [true] but found [false],
Sign up option is still displayed expected [false] but found [true]
at assertions.SoftAssertsInTestNG.toVerifyUserCanLoginWithValidUserNameAndPassword(SoftAssertsInTestNG.java:21)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- toVerifyUserCanLoginWithValidUserNameAndPassword -->
  <testcase name="toVerifyUserCanNotLoginWithInvalidCredentials" time="0.001" classname="assertions.SoftAssertsInTestNG"/>
  <testcase name="verifyUserCanBeDeleted" time="0.014" classname="assertions.SoftAssertsInTestNG">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Object still null expected object to not be null">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Object still null expected object to not be null
at assertions.SoftAssertsInTestNG.verifyUserCanBeDeleted(SoftAssertsInTestNG.java:42)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserCanBeDeleted -->
  <testcase name="verifyUserCountGetsReduced" time="0.01" classname="assertions.SoftAssertsInTestNG">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at assertions.SoftAssertsInTestNG.verifyUserCountGetsReduced(SoftAssertsInTestNG.java:51)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- verifyUserCountGetsReduced -->
  <testcase name="toVerifyUserCanLoginWithValidUserNameAndPassword" time="0.001" classname="misleneouse.InvocationCount"/>
  <testcase name="toVerifyUserCanLoginWithValidUserNameAndPassword" time="0.002" classname="misleneouse.InvocationCount"/>
  <testcase name="toVerifyUserCanLoginWithValidUserNameAndPassword" time="0.001" classname="misleneouse.InvocationCount"/>
  <testcase name="toVerifyUserCanLoginWithValidUserNameAndPassword" time="0.001" classname="misleneouse.InvocationCount"/>
  <testcase name="toVerifyUserCanLoginWithValidUserNameAndPassword" time="0.001" classname="misleneouse.InvocationCount"/>
  <testcase name="toVerifyUserCanNotLoginWithInvalidCredentials" time="0.001" classname="misleneouse.InvocationCount">
    <failure type="java.lang.AssertionError" message="Username is not matching expected [abcd] but found [ABCD]">
      <![CDATA[java.lang.AssertionError: Username is not matching expected [abcd] but found [ABCD]
at misleneouse.InvocationCount.toVerifyUserCanNotLoginWithInvalidCredentials(InvocationCount.java:21)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- toVerifyUserCanNotLoginWithInvalidCredentials -->
  <testcase name="toVerifyUserCanNotLoginWithInvalidCredentials" time="0.021" classname="misleneouse.EnableInTestNG">
    <failure type="java.lang.AssertionError" message="Username is not matching expected [abcd] but found [ABCD]">
      <![CDATA[java.lang.AssertionError: Username is not matching expected [abcd] but found [ABCD]
at misleneouse.EnableInTestNG.toVerifyUserCanNotLoginWithInvalidCredentials(EnableInTestNG.java:21)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- toVerifyUserCanNotLoginWithInvalidCredentials -->
  <testcase name="verifyCredentialsOfUser" time="0.003" classname="dataprovider.DataProviderClasss"/>
  <testcase name="verifyCredentialsOfUser" time="0.002" classname="dataprovider.DataProviderClasss"/>
  <testcase name="brockenLinkMethod" time="24.181" classname="brockenlink.BrockenLinkClass2"/>
  <testcase name="sample" time="27.855" classname="screencap.ScreenCaptureClass2">
    <failure type="java.lang.AssertionError" message="expected [adfgdgfdg] but found [3435345]">
      <![CDATA[java.lang.AssertionError: expected [adfgdgfdg] but found [3435345]
at screencap.ScreenCaptureClass2.sample(ScreenCaptureClass2.java:56)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- sample -->
  <testcase name="verifyNewUserCanBeAddedInSystem" time="7.77" classname="dataprovider.DataProviderClasss2"/>
  <testcase name="verifyNewUserCanBeAddedInSystem" time="2.341" classname="dataprovider.DataProviderClasss2"/>
  <testcase name="verifyUserCanBeAdded" time="0.005" classname="annotations.AnnotationClass2"/>
  <testcase name="verifyUserCanBeEdited" time="0.0" classname="annotations.AnnotationClass2"/>
  <testcase name="verifyUserCanBeDeleted" time="0.001" classname="annotations.AnnotationClass3"/>
  <testcase name="verifyUserCountGetsReduced" time="0.002" classname="annotations.AnnotationClass3"/>
  <testcase name="verifyUserCountGetsReduced" time="0.001" classname="misleneouse.DependentTestCases">
    <skipped/>
  </testcase> <!-- verifyUserCountGetsReduced -->
  <testcase name="verifyFileCanBeUploaded" time="44.726" classname="screencap.ScreenCaptureClass"/>
  <testcase name="verifyFileCanBeUploaded" time="16.552" classname="screencap.ScreenCaptureClass2">
    <failure type="java.lang.AssertionError" message="expected [1 file
has been successfully ] but found [1 file
has been successfully uploaded.]">
      <![CDATA[java.lang.AssertionError: expected [1 file
has been successfully ] but found [1 file
has been successfully uploaded.]
at screencap.ScreenCaptureClass2.verifyFileCanBeUploaded(ScreenCaptureClass2.java:47)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- verifyFileCanBeUploaded -->
  <testcase name="brockenLinkMethod" time="235.348" classname="brockenlink.BrockenLinkClass6">
    <failure type="org.openqa.selenium.NoSuchWindowException" message="no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=108.0.5359.73)
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:17:03&amp;apos;
System info: host: &amp;apos;LAPTOP-D2GVCL39&amp;apos;, ip: &amp;apos;192.168.29.64&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_261&amp;apos;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 108.0.5359.73, chrome: {chromedriverVersion: 107.0.5304.62 (1eec40d3a576..., userDataDir: C:\Users\91992\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:55606}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: e1b55a7158fd12d1aedb4db0b759b7a2
*** Element info: {Using=tag name, value=a}">
      <![CDATA[org.openqa.selenium.NoSuchWindowException: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=108.0.5359.73)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'LAPTOP-D2GVCL39', ip: '192.168.29.64', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_261'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 108.0.5359.73, chrome: {chromedriverVersion: 107.0.5304.62 (1eec40d3a576..., userDataDir: C:\Users\91992\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:55606}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: e1b55a7158fd12d1aedb4db0b759b7a2
*** Element info: {Using=tag name, value=a}
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:353)
at org.openqa.selenium.remote.RemoteWebDriver.findElementsByTagName(RemoteWebDriver.java:400)
at org.openqa.selenium.By$ByTagName.findElements(By.java:312)
at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:311)
at brockenlink.BrockenLinkClass6.brockenLinkMethod(BrockenLinkClass6.java:30)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- brockenLinkMethod -->
  <testcase name="@AfterSuite afterSuiteAnnotation" time="0.0" classname="testbase.TestBase">
    <ignored/>
  </testcase> <!-- @AfterSuite afterSuiteAnnotation -->
  <testcase name="@AfterSuite afterSuiteAnnotation" time="0.0" classname="testbase.TestBase">
    <ignored/>
  </testcase> <!-- @AfterSuite afterSuiteAnnotation -->
  <testcase name="@AfterTest afterTestAnnotation" time="0.0" classname="testbase.TestBase">
    <ignored/>
  </testcase> <!-- @AfterTest afterTestAnnotation -->
  <testcase name="@AfterTest afterTestAnnotation" time="0.0" classname="testbase.TestBase">
    <ignored/>
  </testcase> <!-- @AfterTest afterTestAnnotation -->
  <testcase name="@BeforeSuite beforeSuiteAnnotation" time="0.0" classname="testbase.TestBase">
    <ignored/>
  </testcase> <!-- @BeforeSuite beforeSuiteAnnotation -->
  <testcase name="@BeforeSuite beforeSuiteAnnotation" time="0.0" classname="testbase.TestBase">
    <ignored/>
  </testcase> <!-- @BeforeSuite beforeSuiteAnnotation -->
  <testcase name="@BeforeTest beforeTestAnnotation" time="0.0" classname="testbase.TestBase">
    <ignored/>
  </testcase> <!-- @BeforeTest beforeTestAnnotation -->
  <testcase name="@BeforeTest beforeTestAnnotation" time="0.0" classname="testbase.TestBase">
    <ignored/>
  </testcase> <!-- @BeforeTest beforeTestAnnotation -->
  <testcase name="verifyUserCanBeAdded" time="0.0" classname="dataprovider.DataProviderClasss">
    <ignored/>
  </testcase> <!-- verifyUserCanBeAdded -->
  <testcase name="toVerifyUserCanLoginWithValidUserNameAndPassword" time="0.0" classname="misleneouse.EnableInTestNG">
    <ignored/>
  </testcase> <!-- toVerifyUserCanLoginWithValidUserNameAndPassword -->
</testsuite> <!-- Regression -->
