<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="LAPTOP-D2GVCL39" name="misleneouse.DependentTestCases" tests="3" failures="1" timestamp="2022-12-06T21:07:57 IST" time="0.062" errors="0">
  <testcase name="verifyUserCountGetsReduced" time="0.001" classname="misleneouse.DependentTestCases">
    <skipped/>
  </testcase> <!-- verifyUserCountGetsReduced -->
  <system-out/>
  <testcase name="toVerifyUserCanLoginWithValidUserNameAndPassword" time="0.003" classname="misleneouse.DependentTestCases"/>
  <system-out/>
  <testcase name="toVerifyUsedCanSendEmail" time="0.058" classname="misleneouse.DependentTestCases">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Username is not matching expected [ertertet] but found [ABCD]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Username is not matching expected [ertertet] but found [ABCD]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at misleneouse.DependentTestCases.toVerifyUsedCanSendEmail(DependentTestCases.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- toVerifyUsedCanSendEmail -->
  <system-out/>
</testsuite> <!-- misleneouse.DependentTestCases -->
